server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC
    username: root
    password: 123456789
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.leyou.userservice.pojo
